[package]
name = "cobapi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engage = { git = "https://github.com/atarng/engage", branch="gender_equality.test" }
